---
- name: create gnupg directory
  file:
    path: "{{ __gnupg_directory }}"
    state: directory
    mode: "0700"

- name: template configuration
  template:
    src: templates/gpg.j2
    dest: "{{ item.target }}"
    backup: "{{ __gnupg_create_backup }}"
    mode: "0644"
  with_items:
    - target: "{{ __gnupg_directory }}/gpg.conf"
      config: "{{ gnupg_gpg_conf }}"
    - target: "{{ __gnupg_directory }}/gpg-agent.conf"
      config: "{{ gnupg_gpg_agent_conf }}"
    - target: "{{ __gnupg_directory }}/scdaemon.conf"
      config: "{{ gnupg_scdaemon_conf }}"
